<a href="https://colab.research.google.com/github/yj4976s-cpu/AI_26/blob/main/%ED%8C%90%EB%8B%A4%EC%8A%A4_%EA%B3%B5%EB%B6%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd # 판다스를 pd라는 별칭으로 불러옴

# 파이썬 리스트를 통해 시리즈 생성
series_data = pd.Series([True, 3.14, 'ABC'])

# 데이터 타입과 시리즈 출력
print(type(series_data))
print(series_data)

<class 'pandas.core.series.Series'>
0    True
1    3.14
2     ABC
dtype: object

In [ ]:
import pandas as pd

# 파이썬 딕셔너리를 통해 데이터 프레임 생성
df = pd.DataFrame({'c0': [1,2,3], 'c1' : [4,5,6]})

# 데이터 타입과 데이터프레임 출력
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>

   c0  c1
0   1   4
1   2   5
2   3   6

In [ ]:
import pandas as pd
import numpy as np

# 딕셔너리에 넷플릭스 데이터 할당하기
# 'show_id' 열과 'type' 열만 적어보세요!
dict_netflix = {
    'show_id':[1, 2, 3, 4, 5, 6, 7, 8],
    'type':['TV Show', 'Movie', 'Movie', 'TV Show', 'Movie', 'Movie', 'TV Show', 'Movie'],
    'title':['Squid Game', 'Stranger Things', 'Sherlock Holmes', 'Iron Man & Captain America: Heroes United', 'Bird Box', 'Anne with an E', 'About Time','Inception'],
    'director':[np.nan, np.nan, 'Guy Ritchie', 'Leo Riley', 'Susanne Bier', np.nan, 'Richard Curtis', 'Christopher Nolan'],
    'cast':['Lee Jung-jae', 'Winona Ryder', 'Robert Downey Jr', 'Adrian Pasdar', 'Sandra Bullock','Amybeth McNulty', 'Domhnall Gleeson', 'Leonardo DiCaprio'],
    'country':[np.nan, 'United States', 'United States, Germany', 'United States', 'United States', 'Canada', np.nan, 'United States'],
    'release_year':[2021, 2019, 2009, 2014, 2018, 2019, 2013, 2010],
    'duration':[300, 800, 128, 71, 124, 900, 123, 148],
    'listed_in':[np.nan, 'TV Horror', 'Action & Adventure', np.nan, np.nan, np.nan,np.nan, np.nan]}

# 딕셔너리로 데이터프레임 생성하기
netflix = pd.DataFrame(dict_netflix)

netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,Movie,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,TV Show,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,Movie,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
6,7,TV Show,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [ ]:
import pandas as pd
netflix = pd.read_csv("./netflix_selena.csv")
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [ ]:
netflix.to_csv("./netflix_new.csv", index=False)

In [ ]:
import pandas as pd
netflix = pd.read_csv('netflix_selena.csv')
# 열 이름 확인
list(netflix.columns)

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'release_year',
 'duration',
 'listed_in']

In [ ]:
list(netflix.index)

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
list(netflix.index)

[0, 1, 2, 3, 4, 5, 6, 7]

In [ ]:
netflix.index = ["1행", "2행", "3행", "4행", "5행", "6행", "7행", "8행"]
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
1행,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
2행,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
3행,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
4행,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
5행,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
6행,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
7행,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
8행,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [ ]:
netflix.loc["3행"]

show_id                              3
type                             Movie
title                  Sherlock Holmes
director                   Guy Ritchie
cast                  Robert Downey Jr
country         United States, Germany
release_year                      2009
duration                           128
listed_in           Action & Adventure
Name: 3행, dtype: object

In [ ]:
# 데이터 처음 5개의 행 출력
netflix.head()

,show_id,type,title,director,cast,country,release_year,duration,listed_in
1행,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
2행,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
3행,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
4행,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
5행,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN

In [ ]:
# 데이터 마지막 5개의 행 출력
netflix.tail()

,show_id,type,title,director,cast,country,release_year,duration,listed_in
4행,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
5행,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
6행,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
7행,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
8행,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [ ]:
# 행과 열의 개수 확인
netflix.shape

(8, 9)

In [ ]:
# 열에 대한 요약 정보 확인
netflix.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 1행 to 8행
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8 non-null      int64
 1   type          8 non-null      object
 2   title         8 non-null      object
 3   director      5 non-null      object
 4   cast          8 non-null      object
 5   country       6 non-null      object
 6   release_year  8 non-null      int64
 7   duration      8 non-null      int64
 8   listed_in     2 non-null      object
dtypes: int64(3), object(6)
memory usage: 940.0+ bytes

In [ ]:
# title 열 선택, 대괄호 안에 열 이름을 따옴표와 함께 입력
title = netflix['title']
title.head()

1행                                   Squid Game
2행                              Stranger Things
3행                              Sherlock Holmes
4행    Iron Man & Captain America: Heroes United
5행                                     Bird Box
Name: title, dtype: object

In [ ]:
#  title 열 선택, 점 다음에 열 이름 입력
title = netflix.title
title.head()

1행                                   Squid Game
2행                              Stranger Things
3행                              Sherlock Holmes
4행    Iron Man & Captain America: Heroes United
5행                                     Bird Box
Name: title, dtype: object

In [2]:
import pandas as pd
netflix = pd.read_csv('netflix_selena.csv')
# 2개의 열을 선택하여 데이터 프레임으로 반환, 이중 대괄호 [[]]안에 열 이름 입력
title_release_year = netflix[['title', 'release_year']]
title_release_year.head()

                                       title  release_year
0                                 Squid Game          2021
1                            Stranger Things          2019
2                            Sherlock Holmes          2009
3  Iron Man & Captain America: Heroes United          2014
4                                   Bird Box          2018

In [5]:
title = netflix[['title']]
title.head()

                                       title
0                                 Squid Game
1                            Stranger Things
2                            Sherlock Holmes
3  Iron Man & Captain America: Heroes United
4                                   Bird Box

In [6]:
# 2015년 이후에 나온 콘텐츠만 추출(True, False 반환)
netflix['release_year'] > 2015

0     True
1     True
2    False
3    False
4     True
5     True
6    False
7    False
Name: release_year, dtype: bool

In [7]:
# 2015년 이후에 나온 콘텐츠 추출
more2015 = netflix[netflix['release_year']>2015]
more2015.head()

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN

In [9]:
# 2015이전에 나온 콘텐츠만 추출
less2015 = netflix[~(netflix['release_year']>2015)]
less2015.head()

,show_id,type,title,director,cast,country,release_year,duration,listed_in
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [10]:
# 2015 이후에 나온 콘텐츠 이면서(&) 쇼의 장르가 TV show인 데이터 추출
(netflix['release_year']>2015) & (netflix['type']=='TV Show')

0     True
1     True
2    False
3    False
4    False
5     True
6    False
7    False
dtype: bool

In [12]:
more_2015_tv = netflix[(netflix['release_year']>2015) & (netflix['type']=='TV Show')]
more_2015_tv.head()

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN

In [14]:
# 조건 :2015년 이후에 나온 콘텐츠이거나(|) 쇼의 장르가 TV SHOW인 데이터 추출
more_or_tv = netflix[(netflix['release_year']>2015) | (netflix['type']=='TV Show')]
more_or_tv.head()

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN

In [4]:
import pandas as pd
netflix = pd.read_csv('netflix_selena.csv')
# loc[] : 데이터프레임의 행과 열의 이름을 사용
# 전체 행과 title과 release_year의 열을 출력
title_year = netflix.loc[ : , ['title', 'release_year']]
title_year.head()

                                       title  release_year
0                                 Squid Game          2021
1                            Stranger Things          2019
2                            Sherlock Holmes          2009
3  Iron Man & Captain America: Heroes United          2014
4                                   Bird Box          2018

In [5]:
# .loc[] : 데이터프레임의 행과 열의 이름을 사용
# 0번째,1번째 행과 title과 release_year의 열을 출력
title_year = netflix.loc[[0, 1], ['title', 'release_year']]
title_year.head()

             title  release_year
0       Squid Game          2021
1  Stranger Things          2019

In [6]:
# .index : 행 이름 변경
netflix.index = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
# .loc[] : 데이터프레임의 행과 열의 이름을 사용
# B, C행과 title과 release_year의 열을 출력
title_year = netflix.loc[['B', 'C'], ['title', 'release_year']]
title_year.head()

             title  release_year
B  Stranger Things          2019
C  Sherlock Holmes          2009

In [7]:
# iloc[] : 데이터프레임의 행과 열 번호를 사용
#  3번째, 4번째 행과 1번째, 3번째 열을 출력
type_director = netflix.iloc[[3,4], [1, 3]]
type_director.head()

    type      director
D  Movie     Leo Riley
E  Movie  Susanne Bier

In [8]:
#  0번쩨 행, 0번째 열의 값을 'NO Type'변경
type_director.iloc[0,0] = 'No Type'
type_director.head()

      type      director
D  No Type     Leo Riley
E    Movie  Susanne Bier

In [9]:
# .isin(values) : 각 요소가 values에 포함된 값인지 파악하여 True/False 반환
# type 변수의 값이 TV Show일 경우는 True 반환, 아니라면 False 반환
netflix['type'].isin(['TV Show'])

A     True
B     True
C    False
D    False
E    False
F     True
G    False
H    False
Name: type, dtype: bool

In [10]:
# 논리형 인덱싱 + .isin() : 데이터의 특정 범위만 추출
# type변수의 값이 TV Show일 경우만 추출하여 TV_Show 저장
TV_Show = netflix[netflix['type'].isin(['TV Show'])]
TV_Show.head()

,show_id,type,title,director,cast,country,release_year,duration,listed_in
A,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
B,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
F,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN

In [11]:
# 결측치 확인 (1) - .isna().sum()
netflix.isna().sum()

show_id         0
type            0
title           0
director        3
cast            0
country         2
release_year    0
duration        0
listed_in       6
dtype: int64

In [12]:
# 결측치 확인(2) - .info()
netflix.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, A to H
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8 non-null      int64
 1   type          8 non-null      object
 2   title         8 non-null      object
 3   director      5 non-null      object
 4   cast          8 non-null      object
 5   country       6 non-null      object
 6   release_year  8 non-null      int64
 7   duration      8 non-null      int64
 8   listed_in     2 non-null      object
dtypes: int64(3), object(6)
memory usage: 940.0+ bytes

In [13]:
# 결측치 확인(3) - .for문
for i in netflix.columns:
    missingValueRate = netflix[i].isna().sum()/len(netflix) *100
    if missingValueRate > 0:
        print("{} null rate: {}%".format(i, round(missingValueRate, 2 )))

director null rate: 37.5%
country null rate: 25.0%
listed_in null rate: 75.0%

In [14]:
# 결측치 처리(1) - fillna()
# 결측치 비율 : country(25.0%) : 8개 중에 2개 결측치
netflix['country'] = netflix['country'].fillna('No Data')
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
A,1,TV Show,Squid Game,NaN,Lee Jung-jae,No Data,2021,300,NaN
B,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
C,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
D,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
E,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
F,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
G,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,No Data,2013,123,NaN
H,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [17]:
import numpy as np
# 결측치 처리 (2) - replace()
# 결측치 비율 : director(37.5%) : 8개 중에 3개 결측치
netflix['director'] = netflix['director'].replace(np.nan, 'No Data')
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
A,1,TV Show,Squid Game,No Data,Lee Jung-jae,No Data,2021,300,NaN
B,2,TV Show,Stranger Things,No Data,Winona Ryder,United States,2019,800,TV Horror
C,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
D,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
E,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
F,6,TV Show,Anne with an E,No Data,Amybeth McNulty,Canada,2019,900,NaN
G,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,No Data,2013,123,NaN
H,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [19]:
# 결측치 처리 (3) - dropna()
# 결측치 비율 : listed_in(75.0%) : 8개 중에 6개 결측치
netflix.dropna(axis=1, inplace =True)
netflix

,show_id,type,title,director,cast,country,release_year,duration
A,1,TV Show,Squid Game,No Data,Lee Jung-jae,No Data,2021,300
B,2,TV Show,Stranger Things,No Data,Winona Ryder,United States,2019,800
C,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128
D,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71
E,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124
F,6,TV Show,Anne with an E,No Data,Amybeth McNulty,Canada,2019,900
G,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,No Data,2013,123
H,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148

In [20]:
netflix = pd.read_csv('netflix_selena.csv')
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
0,1,TV Show,Squid Game,NaN,Lee Jung-jae,NaN,2021,300,NaN
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71,NaN
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124,NaN
5,6,TV Show,Anne with an E,NaN,Amybeth McNulty,Canada,2019,900,NaN
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,NaN,2013,123,NaN
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,NaN

In [21]:
netflix.dropna(subset=['listed_in'], inplace =True)
netflix

,show_id,type,title,director,cast,country,release_year,duration,listed_in
1,2,TV Show,Stranger Things,NaN,Winona Ryder,United States,2019,800,TV Horror
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128,Action & Adventure

In [22]:
import pandas as pd
import numpy as np
netflix = pd.read_csv('netflix_selena.csv')
netflix['country'] = netflix['country'].fillna('No Data')
netflix['director'] = netflix['director'].replace(np.nan, 'No Data')
netflix.dropna(axis=1, inplace =True)
netflix

,show_id,type,title,director,cast,country,release_year,duration
0,1,TV Show,Squid Game,No Data,Lee Jung-jae,No Data,2021,300
1,2,TV Show,Stranger Things,No Data,Winona Ryder,United States,2019,800
2,3,Movie,Sherlock Holmes,Guy Ritchie,Robert Downey Jr,"United States, Germany",2009,128
3,4,Movie,Iron Man & Captain America: Heroes United,Leo Riley,Adrian Pasdar,United States,2014,71
4,5,Movie,Bird Box,Susanne Bier,Sandra Bullock,United States,2018,124
5,6,TV Show,Anne with an E,No Data,Amybeth McNulty,Canada,2019,900
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,No Data,2013,123
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148

In [23]:
# 결측치 처리한 데이터 csv 파일로 저장
netflix.to_csv('netflix_cleaned.csv', index=False)

In [1]:
import pandas as pd

# 결측치 처리가 완료된 데이터 불러오기
netflix= pd.read_csv('netflix_cleaned.csv')
# duration 열의 평균값, 중앙값, 합, 최솟값, 최댓값 구하기
print('mean :',netflix['duration'].mean())
print('median :',netflix['duration'].median())
print('sum :', netflix['duration'].sum())
print('min :',netflix['duration'].min())
print('max :',netflix['duration'].max())

mean : 324.25
median : 138.0
sum : 2594
min : 71
max : 900

In [2]:
# duration 열의 표준편차, 분산 구하기
print('std :',netflix['duration'].std())
print('var :',netflix['duration'].var())

std : 332.2497984520511
var : 110389.92857142857

In [3]:
# type열의 비어있지 않은 값의 개수와 빈도수 구하기
print('count :',netflix['type'].count())
print('value_counts :',netflix['type'].value_counts())

count : 8
value_counts : type
Movie      5
TV Show    3
Name: count, dtype: int64

In [5]:
# 주요 통계량 요약
print(netflix[['release_year','duration']].describe())

       release_year    duration
count      8.000000    8.000000
mean    2015.375000  324.250000
std        4.501984  332.249798
min     2009.000000   71.000000
25%     2012.250000  123.750000
50%     2016.000000  138.000000
75%     2019.000000  425.000000
max     2021.000000  900.000000

In [6]:
# 원하는 통계량 요약
netflix.agg({'release_year': ['min', 'max', 'median', 'std'],
             'duration' :['min','max','mean','median']})

        release_year  duration
min      2009.000000     71.00
max      2021.000000    900.00
median   2016.000000    138.00
std         4.501984       NaN
mean             NaN    324.25

In [7]:
netflix.agg({'release_year': ['min', 'max', 'median', 'std','mean'],
             'duration' :['min','max','mean','median']})

        release_year  duration
min      2009.000000     71.00
max      2021.000000    900.00
median   2016.000000    138.00
std         4.501984       NaN
mean     2015.375000    324.25

In [12]:
import pandas as pd
netflix = pd.read_csv('netflix_cleaned.csv')
# 시리즈 타입의 그룹별 집계
# groupby를 통해 type열을 묶은 다음, duration열의 평균 구하기
netflix.groupby('type')['duration'].mean()

type
Movie      118.800000
TV Show    666.666667
Name: duration, dtype: float64

In [14]:
# 데이터프레임 타입의 그룹별 집계
# groupby로 type과 country열로 묶어주고 release_year과 duration열의 평균 구하기
netflix.groupby(['type', 'country'])[['release_year','duration']].mean()

                                release_year    duration
type    country
Movie   No Data                       2013.0  123.000000
        United States                 2014.0  114.333333
        United States, Germany        2009.0  128.000000
TV Show Canada                        2019.0  900.000000
        No Data                       2021.0  300.000000
        United States                 2019.0  800.000000

In [15]:
# 행 추가 : dataframe.loc[index] = values
new = netflix.iloc[0,:] # 첫 번째 행 선택
netflix.loc[8]= new # 새로운 행 추가
netflix.tail(2) # 마지막 두 개 행 출력

,show_id,type,title,director,cast,country,release_year,duration
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148
8,1,TV Show,Squid Game,No Data,Lee Jung-jae,No Data,2021,300

In [17]:
# 행 추가 : dataframe.loc['new_column'] = values

netflix['2duration']= netflix['duration']*2 # 새로운 열 추가
netflix.head(2) # 마지막 두 개 행 출력 # 결과 확인

,show_id,type,title,director,cast,country,release_year,duration,2duration
0,1,TV Show,Squid Game,No Data,Lee Jung-jae,No Data,2021,300,600
1,2,TV Show,Stranger Things,No Data,Winona Ryder,United States,2019,800,1600

In [19]:
import numpy as np
netflix=netflix.drop(np.arange(2, 5), axis=0) # 행 삭제
netflix

,show_id,type,title,director,cast,country,release_year,duration,2duration
0,1,TV Show,Squid Game,No Data,Lee Jung-jae,No Data,2021,300,600
1,2,TV Show,Stranger Things,No Data,Winona Ryder,United States,2019,800,1600
5,6,TV Show,Anne with an E,No Data,Amybeth McNulty,Canada,2019,900,1800
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,No Data,2013,123,246
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148,296
8,1,TV Show,Squid Game,No Data,Lee Jung-jae,No Data,2021,300,600

In [20]:
netflix=netflix.drop('2duration', axis=1) # 열 삭제
netflix

,show_id,type,title,director,cast,country,release_year,duration
0,1,TV Show,Squid Game,No Data,Lee Jung-jae,No Data,2021,300
1,2,TV Show,Stranger Things,No Data,Winona Ryder,United States,2019,800
5,6,TV Show,Anne with an E,No Data,Amybeth McNulty,Canada,2019,900
6,7,Movie,About Time,Richard Curtis,Domhnall Gleeson,No Data,2013,123
7,8,Movie,Inception,Christopher Nolan,Leonardo DiCaprio,United States,2010,148
8,1,TV Show,Squid Game,No Data,Lee Jung-jae,No Data,2021,300

In [21]:
# 판다스, 넘파이 라이브러리 불러오기
import pandas as pd
import numpy as np
# 파이썬 딕셔너리 정의
customer_dic = {
'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace','Hyemin'],
'comment_length': [150, 200, 50, 300, 120, 180, 75, 160],
'likes': [25, 30, 10, 45, 20, 35, 5, 28],
'is_spam': [False, False, True, np.nan, False, True, np.nan, False],
'has_image': [True, False, True, True, False, False, True, True]
}

# 판다스 데이터프레임 생성
customer = pd.DataFrame(customer_dic)

# 결과 확인
customer

      name  comment_length  likes is_spam  has_image
0    Alice             150     25   False       True
1      Bob             200     30   False      False
2  Charlie              50     10    True       True
3    David             300     45     NaN       True
4      Eve             120     20   False      False
5    Frank             180     35    True      False
6    Grace              75      5     NaN       True
7   Hyemin             160     28   False       True

In [22]:
# 결측치 처리
customer['is_spam'] = customer['is_spam'].fillna(False)

# 데이터프레임 내용 확인
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            8 non-null      object
 1   comment_length  8 non-null      int64
 2   likes           8 non-null      int64
 3   is_spam         8 non-null      bool
 4   has_image       8 non-null      bool
dtypes: bool(2), int64(2), object(1)
memory usage: 340.0+ bytes

/tmp/ipython-input-260/2879500835.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  customer['is_spam'] = customer['is_spam'].fillna(False)

In [23]:
# 그룹화와 집계함수 처리
customer.groupby('has_image')['likes'].mean()

has_image
False    28.333333
True     22.600000
Name: likes, dtype: float64

In [24]:
# 조건 설정(비교연산자, 논리연산자)
# 댓글 길이 100자 이상, 좋아요 20개 이상, 스팸 댓글이 아닌 글, 이미지가 포함된 글
condition = (
(customer['comment_length'] >= 100) &
(customer['likes'] >= 20) &
(customer['is_spam'] == False) &
(customer['has_image'])
)

# 조건을 만족하는 데이터 필터
winners = customer[condition]

# 결과 확인
winners

     name  comment_length  likes  is_spam  has_image
0   Alice             150     25    False       True
3   David             300     45    False       True
7  Hyemin             160     28    False       True

In [26]:
# 이름만 추출하여 시리즈 생성
name_series = customer['name']

# 하위 3줄 출력
print(name_series.tail(3))

5     Frank
6     Grace
7    Hyemin
Name: name, dtype: object

In [27]:
# 'customer.csv' 파일로 데이터 저장
customer.to_csv('customer.csv', index=False)

In [28]:
# 'customer.csv' 파일 불러오기
loaded_customer = pd.read_csv('customer.csv')

# 상위 5개의 데이터 출력
loaded_customer.head()

      name  comment_length  likes  is_spam  has_image
0    Alice             150     25    False       True
1      Bob             200     30    False      False
2  Charlie              50     10     True       True
3    David             300     45    False       True
4      Eve             120     20    False      False